"""Multi-mode operator: Ulam spiral quadratic families as independent modes.

THE INSIGHT (from the Ulam spiral image):
  Primes aren't uniformly distributed — they cluster along QUADRATIC
  POLYNOMIAL FAMILIES f(n) = an^2 + bn + c. Each family appears as a
  diagonal direction in the Ulam spiral. There are ~6-8 visible families.

  Our current kernel treats all primes equally:
    K(d,T) = sum_p log(p)/p^{m/2} * cos(2*pi*d*m*log(p)/log(T))

  But primes from DIFFERENT quadratic families contribute differently
  to the pair correlation. Each family is a separate MODE of the operator.

APPROACH:
  1. Classify primes by their quadratic residue class (mod small numbers)
     — this approximates the Ulam spiral directional families
  2. Build a separate kernel for each class
  3. Give each class its own coupling constant
  4. The full off-diagonal: H_{k,k+d} = sum_families C_i * K_i(d, T_k)

The quadratic families in the Ulam spiral correspond to:
  - Primes = 1 (mod 4) vs 3 (mod 4)  [the two main diagonals]
  - Primes = 1,2,3,4,5,6 (mod various) [finer structure]
  - Primes generated by specific quadratics (Euler's n^2+n+41, etc.)

More precisely, the Ulam spiral diagonals are:
  Direction 1: 4n^2 + 0n + c  (horizontal)
  Direction 2: 4n^2 + 2n + c  (diagonal)
  Direction 3: 4n^2 + 4n + c  (vertical, shifted)
  etc.
The key discriminant is b^2 - 16c, and primes cluster where
the class number h(b^2-16c) is small.
"""
import sys
import time

sys.path.insert(0, "src")
import numpy as np
from scipy.linalg import eigh
from scipy.optimize import minimize
import mpmath

t0 = time.time()
mpmath.mp.dps = 20

# ============================================================
# Setup
# ============================================================
print("Computing 500 zeta zeros...")
t_start = time.time()
N = 500
zeta_zeros = np.array([float(mpmath.im(mpmath.zetazero(k))) for k in range(1, N + 1)])
print(f"  Done ({time.time()-t_start:.1f}s)")

from sympy import primerange
all_primes = list(primerange(2, 2000))

trim = int(0.1 * N)
mean_spacing = np.mean(np.diff(zeta_zeros[trim:-trim]))


def N_deriv(T):
    if T < 2: return 0.001
    return np.log(T/(2*np.pi)) / (2*np.pi)

def weyl_zero(n):
    t = 2*np.pi*n / np.log(max(n,2)+2)
    for _ in range(30):
        if t < 1: t = 10.0
        Nt = t/(2*np.pi)*np.log(t/(2*np.pi)) - t/(2*np.pi) + 7/8
        dNt = N_deriv(t)
        if abs(dNt) < 1e-30: break
        t -= (Nt - n) / dNt
    return t

def S_func(T, primes, max_m=3):
    s = 0.0
    for p in primes:
        lp = np.log(p)
        for m in range(1, max_m+1):
            s -= np.sin(2*m*T*lp) / (m * p**(m/2))
    return s / np.pi

def build_alpha(N_size, primes, max_m=3):
    alpha = np.zeros(N_size)
    for k in range(1, N_size+1):
        T_w = weyl_zero(k)
        dN = N_deriv(T_w)
        alpha[k-1] = T_w + S_func(T_w, primes, max_m) / dN
    return alpha


# Build alpha
print("Building alpha...")
alpha = build_alpha(N, all_primes[:168], max_m=5)


# ============================================================
# Classify primes into quadratic families
# ============================================================
print("\nClassifying primes into Ulam spiral families...")

def classify_primes(primes):
    """Classify primes by residue classes — approximating Ulam families.

    The Ulam spiral's diagonal lines come from primes in specific
    residue classes. The key moduli are:
      mod 4:  two families (1 mod 4, 3 mod 4) — the main diagonals
      mod 6:  two families (1 mod 6, 5 mod 6) — hexagonal structure
      mod 3:  primes = 1 vs 2 mod 3
      mod 8:  four families (1,3,5,7 mod 8) — finer diagonal structure
      mod 12: four families (1,5,7,11) — combines mod 3 and mod 4

    Also classify by quadratic character:
      Primes where -1 is a QR (p = 1 mod 4) — one spiral direction
      Primes where 2 is a QR (p = ±1 mod 8) — another direction
      Primes where 3 is a QR (p = ±1 mod 12) — another direction
    """
    families = {}

    # Mod 4 (the two main Ulam diagonals)
    families["p=1(4)"] = [p for p in primes if p % 4 == 1]
    families["p=3(4)"] = [p for p in primes if p % 4 == 3]

    # Mod 6
    families["p=1(6)"] = [p for p in primes if p % 6 == 1]
    families["p=5(6)"] = [p for p in primes if p % 6 == 5]

    # Mod 8 (four directions)
    families["p=1(8)"] = [p for p in primes if p % 8 == 1]
    families["p=3(8)"] = [p for p in primes if p % 8 == 3]
    families["p=5(8)"] = [p for p in primes if p % 8 == 5]
    families["p=7(8)"] = [p for p in primes if p % 8 == 7]

    # Quadratic residue families
    families["QR(-1)"] = [p for p in primes if p % 4 == 1]  # -1 is QR mod p
    families["QR(2)"] = [p for p in primes if p % 8 in (1, 7)]  # 2 is QR mod p
    families["QR(3)"] = [p for p in primes if p % 12 in (1, 11)]  # 3 is QR mod p
    families["QR(5)"] = [p for p in primes if p % 5 in (1, 4)]  # 5 is QR mod p
    families["QR(-3)"] = [p for p in primes if p % 3 == 1]  # -3 is QR mod p

    # Euler's polynomial family: primes of form n^2 + n + 41
    euler_primes = set()
    for n_val in range(200):
        val = n_val**2 + n_val + 41
        if val in set(primes):
            euler_primes.add(val)
    families["Euler(41)"] = sorted(euler_primes)

    return families


families = classify_primes(all_primes[:303])

print(f"  Families defined:")
for name, plist in sorted(families.items(), key=lambda x: -len(x[1])):
    if len(plist) > 5:
        print(f"    {name:<12}: {len(plist):>4} primes")


# ============================================================
# Build family-specific kernels
# ============================================================

def kernel_family(d, T, primes_subset, max_m=2):
    """Kernel using only primes from one family."""
    log_T = np.log(max(T, 10) / (2*np.pi))
    if log_T < 0.1:
        log_T = 0.1
    val = 0.0
    for p in primes_subset:
        lp = np.log(p)
        for m in range(1, max_m+1):
            amp = lp / (p**(m/2) * log_T)
            val += amp * np.cos(2 * np.pi * d * m * lp / log_T)
    return val


def build_multimode_banded(alpha_vals, family_dict, bandwidth, coupling_dict):
    """Build banded matrix with separate coupling per family.

    H_{k,k+d} = sum_families C_i * K_i(d, T_k)
    """
    n = len(alpha_vals)
    H = np.diag(alpha_vals.copy())

    for k in range(n):
        T_k = alpha_vals[k]
        for d in range(1, bandwidth + 1):
            if k + d < n:
                val = 0.0
                for fname, plist in family_dict.items():
                    if fname in coupling_dict and len(plist) > 0:
                        val += coupling_dict[fname] * kernel_family(d, T_k, plist)
                H[k, k+d] = val
                H[k+d, k] = val

    return H


# ============================================================
# TEST 1: Single-family kernels — which family matters most?
# ============================================================
print("\n" + "=" * 70)
print("TEST 1: SINGLE-FAMILY KERNELS (which family matters most?)")
print("=" * 70)

baseline_err = np.mean(np.abs(alpha - zeta_zeros)[trim:-trim])
W = 3

print(f"\n  Bandwidth={W}, optimizing single coupling constant per family")
print(f"  {'Family':<15} {'n_primes':>10} {'C_opt':>8} {'mean_err':>10} {'improv':>8}")
print(f"  {'-'*55}")

family_results = {}

for fname, plist in sorted(families.items(), key=lambda x: -len(x[1])):
    if len(plist) < 3:
        continue

    from scipy.optimize import minimize_scalar

    def obj(log_c, fp=plist):
        c = np.exp(log_c)
        H = build_multimode_banded(alpha, {fname: fp}, W, {fname: c})
        eigs = np.sort(np.linalg.eigvalsh(H))
        t = int(0.1 * len(eigs))
        return np.mean(np.abs(eigs - zeta_zeros[:len(eigs)])[t:-t])

    res = minimize_scalar(obj, bounds=(-5, 5), method='bounded')
    C_opt = np.exp(res.x)
    err = res.fun
    improv = (1 - err/baseline_err) * 100

    family_results[fname] = (C_opt, err, improv)
    print(f"  {fname:<15} {len(plist):>10} {C_opt:>8.4f} {err:>10.4f} {improv:>+7.1f}%")


# ============================================================
# TEST 2: Top families combined
# ============================================================
print("\n" + "=" * 70)
print("TEST 2: COMBINING TOP FAMILIES")
print("=" * 70)

# Sort families by improvement
ranked = sorted(family_results.items(), key=lambda x: x[1][1])

print(f"\n  Ranked by eigenvalue error:")
for fname, (c, e, imp) in ranked[:10]:
    print(f"    {fname:<15}: err={e:.4f} ({imp:+.1f}%)")

# Combine top 2, 3, 4, ... families
print(f"\n  {'n_families':>12} {'mean_err':>10} {'%<half':>8} {'%<full':>8} {'improv':>8}")
print(f"  {'-'*50}")

for n_fam in [1, 2, 3, 4, 6, 8]:
    top_names = [r[0] for r in ranked[:n_fam]]
    top_couplings = {r[0]: r[1][0] for r in ranked[:n_fam]}
    top_families = {fn: families[fn] for fn in top_names}

    # Joint optimization (grid search on a global scale factor)
    def obj_joint(log_scale):
        scale = np.exp(log_scale)
        scaled_couplings = {k: v * scale for k, v in top_couplings.items()}
        H = build_multimode_banded(alpha, top_families, W, scaled_couplings)
        eigs = np.sort(np.linalg.eigvalsh(H))
        t = int(0.1 * len(eigs))
        return np.mean(np.abs(eigs - zeta_zeros[:len(eigs)])[t:-t])

    res = minimize_scalar(obj_joint, bounds=(-3, 3), method='bounded')
    scale = np.exp(res.x)
    scaled = {k: v * scale for k, v in top_couplings.items()}

    H = build_multimode_banded(alpha, top_families, W, scaled)
    eigs = np.sort(np.linalg.eigvalsh(H))
    errs = np.abs(eigs - zeta_zeros[:len(eigs)])[trim:-trim]
    ms = np.mean(np.diff(zeta_zeros[trim:-trim]))

    improv = (1 - np.mean(errs)/baseline_err) * 100
    print(f"  {n_fam:>12} {np.mean(errs):>10.4f} "
          f"{np.mean(errs<ms/2)*100:>7.1f}% "
          f"{np.mean(errs<ms)*100:>7.1f}% {improv:>+7.1f}%")


# ============================================================
# TEST 3: Mod 4 decomposition (the two main Ulam diagonals)
# ============================================================
print("\n" + "=" * 70)
print("TEST 3: MOD 4 DECOMPOSITION (two main Ulam diagonals)")
print("=" * 70)

# The two main diagonal families: p = 1 (mod 4) and p = 3 (mod 4)
# These should have DIFFERENT coupling constants
# (In the Ulam spiral, these diagonals have different densities)

fam_mod4 = {
    "p=1(4)": families["p=1(4)"],
    "p=3(4)": families["p=3(4)"],
}

# Optimize two independent coupling constants
from scipy.optimize import minimize as minimize_nd

def obj_2mode(params):
    c1, c2 = np.exp(params[0]), np.exp(params[1])
    couplings = {"p=1(4)": c1, "p=3(4)": c2}
    H = build_multimode_banded(alpha, fam_mod4, W, couplings)
    eigs = np.sort(np.linalg.eigvalsh(H))
    t = int(0.1 * len(eigs))
    return np.mean(np.abs(eigs - zeta_zeros[:len(eigs)])[t:-t])

res = minimize_nd(obj_2mode, [0.0, 0.0], method='Nelder-Mead',
                   options={'maxiter': 200})
c1_opt, c2_opt = np.exp(res.x[0]), np.exp(res.x[1])
err_2mode = res.fun

# Compare to single-mode (all primes together)
def obj_1mode(log_c):
    c = np.exp(log_c)
    couplings = {"all": c}
    fam_all = {"all": all_primes[:303]}
    H = build_multimode_banded(alpha, fam_all, W, couplings)
    eigs = np.sort(np.linalg.eigvalsh(H))
    t = int(0.1 * len(eigs))
    return np.mean(np.abs(eigs - zeta_zeros[:len(eigs)])[t:-t])

res_1 = minimize_scalar(obj_1mode, bounds=(-5, 5), method='bounded')
err_1mode = res_1.fun

H_2m = build_multimode_banded(alpha, fam_mod4, W,
                               {"p=1(4)": c1_opt, "p=3(4)": c2_opt})
eigs_2m = np.sort(np.linalg.eigvalsh(H_2m))
errs_2m = np.abs(eigs_2m - zeta_zeros[:len(eigs_2m)])[trim:-trim]

print(f"\n  Single mode (all primes):    err = {err_1mode:.4f}")
print(f"  Two modes (mod 4 split):     err = {err_2mode:.4f}")
print(f"  Coupling p=1(4): C1 = {c1_opt:.4f}")
print(f"  Coupling p=3(4): C2 = {c2_opt:.4f}")
print(f"  Ratio C1/C2 = {c1_opt/c2_opt:.4f}")
print(f"  Improvement: {(1-err_2mode/err_1mode)*100:+.1f}%")
print(f"  % < half gap: {np.mean(errs_2m < mean_spacing/2)*100:.1f}%")


# ============================================================
# TEST 4: Full mod-8 decomposition (four Ulam directions)
# ============================================================
print("\n" + "=" * 70)
print("TEST 4: MOD 8 DECOMPOSITION (four Ulam directions)")
print("=" * 70)

fam_mod8 = {
    "p=1(8)": families["p=1(8)"],
    "p=3(8)": families["p=3(8)"],
    "p=5(8)": families["p=5(8)"],
    "p=7(8)": families["p=7(8)"],
}

def obj_4mode(params):
    couplings = {
        "p=1(8)": np.exp(params[0]),
        "p=3(8)": np.exp(params[1]),
        "p=5(8)": np.exp(params[2]),
        "p=7(8)": np.exp(params[3]),
    }
    H = build_multimode_banded(alpha, fam_mod8, W, couplings)
    eigs = np.sort(np.linalg.eigvalsh(H))
    t = int(0.1 * len(eigs))
    return np.mean(np.abs(eigs - zeta_zeros[:len(eigs)])[t:-t])

res4 = minimize_nd(obj_4mode, [0.0, 0.0, 0.0, 0.0], method='Nelder-Mead',
                    options={'maxiter': 500})
err_4mode = res4.fun
c_opts = np.exp(res4.x)

H_4m = build_multimode_banded(alpha, fam_mod8, W,
    {"p=1(8)": c_opts[0], "p=3(8)": c_opts[1],
     "p=5(8)": c_opts[2], "p=7(8)": c_opts[3]})
eigs_4m = np.sort(np.linalg.eigvalsh(H_4m))
errs_4m = np.abs(eigs_4m - zeta_zeros[:len(eigs_4m)])[trim:-trim]

print(f"\n  Four modes (mod 8 split): err = {err_4mode:.4f}")
print(f"  Couplings: 1(8)={c_opts[0]:.4f}, 3(8)={c_opts[1]:.4f}, "
      f"5(8)={c_opts[2]:.4f}, 7(8)={c_opts[3]:.4f}")
print(f"  % < half gap: {np.mean(errs_4m < mean_spacing/2)*100:.1f}%")
print(f"  % < full gap: {np.mean(errs_4m < mean_spacing)*100:.1f}%")


# ============================================================
# TEST 5: Quadratic residue decomposition
# ============================================================
print("\n" + "=" * 70)
print("TEST 5: QUADRATIC RESIDUE DECOMPOSITION")
print("=" * 70)

# QR families: split primes by whether small numbers are QRs
qr_fams = {
    "QR(-1)": families["QR(-1)"],
    "QR(2)": families["QR(2)"],
    "QR(3)": families["QR(3)"],
    "QR(5)": families["QR(5)"],
    "QR(-3)": families["QR(-3)"],
}

def obj_qr(params):
    couplings = {}
    for i, fname in enumerate(qr_fams):
        couplings[fname] = np.exp(params[i])
    H = build_multimode_banded(alpha, qr_fams, W, couplings)
    eigs = np.sort(np.linalg.eigvalsh(H))
    t = int(0.1 * len(eigs))
    return np.mean(np.abs(eigs - zeta_zeros[:len(eigs)])[t:-t])

res_qr = minimize_nd(obj_qr, np.zeros(5), method='Nelder-Mead',
                      options={'maxiter': 800})
err_qr = res_qr.fun
c_qr = np.exp(res_qr.x)

H_qr = build_multimode_banded(alpha, qr_fams, W,
    {fn: c for fn, c in zip(qr_fams, c_qr)})
eigs_qr = np.sort(np.linalg.eigvalsh(H_qr))
errs_qr = np.abs(eigs_qr - zeta_zeros[:len(eigs_qr)])[trim:-trim]

print(f"\n  QR decomposition (5 modes): err = {err_qr:.4f}")
for fn, c in zip(qr_fams, c_qr):
    print(f"    {fn:<10}: C = {c:.4f}")
print(f"  % < half gap: {np.mean(errs_qr < mean_spacing/2)*100:.1f}%")
print(f"  % < full gap: {np.mean(errs_qr < mean_spacing)*100:.1f}%")


# ============================================================
# TEST 6: Bandwidth + modes interaction
# ============================================================
print("\n" + "=" * 70)
print("TEST 6: BANDWIDTH x MODES INTERACTION")
print("=" * 70)

print(f"\n  {'W':>4} {'1-mode':>10} {'2-mode(4)':>10} {'4-mode(8)':>10} {'5-mode(QR)':>10}")
print(f"  {'-'*48}")

for W_test in [1, 2, 3, 5, 10]:
    results_row = []

    # 1-mode
    def o1(log_c):
        H = build_multimode_banded(alpha, {"all": all_primes[:303]}, W_test, {"all": np.exp(log_c)})
        e = np.sort(np.linalg.eigvalsh(H))
        t = int(0.1*len(e))
        return np.mean(np.abs(e-zeta_zeros[:len(e)])[t:-t])
    r1 = minimize_scalar(o1, bounds=(-5,5), method='bounded')
    results_row.append(r1.fun)

    # 2-mode mod4
    def o2(params):
        H = build_multimode_banded(alpha, fam_mod4, W_test,
            {"p=1(4)": np.exp(params[0]), "p=3(4)": np.exp(params[1])})
        e = np.sort(np.linalg.eigvalsh(H))
        t = int(0.1*len(e))
        return np.mean(np.abs(e-zeta_zeros[:len(e)])[t:-t])
    r2 = minimize_nd(o2, [0,0], method='Nelder-Mead', options={'maxiter':200})
    results_row.append(r2.fun)

    # 4-mode mod8
    def o4(params):
        cs = {f"p={r}(8)": np.exp(params[i]) for i,r in enumerate([1,3,5,7])}
        H = build_multimode_banded(alpha, fam_mod8, W_test, cs)
        e = np.sort(np.linalg.eigvalsh(H))
        t = int(0.1*len(e))
        return np.mean(np.abs(e-zeta_zeros[:len(e)])[t:-t])
    r4 = minimize_nd(o4, np.zeros(4), method='Nelder-Mead', options={'maxiter':300})
    results_row.append(r4.fun)

    # 5-mode QR
    def o5(params):
        cs = {fn: np.exp(params[i]) for i,fn in enumerate(qr_fams)}
        H = build_multimode_banded(alpha, qr_fams, W_test, cs)
        e = np.sort(np.linalg.eigvalsh(H))
        t = int(0.1*len(e))
        return np.mean(np.abs(e-zeta_zeros[:len(e)])[t:-t])
    r5 = minimize_nd(o5, np.zeros(5), method='Nelder-Mead', options={'maxiter':500})
    results_row.append(r5.fun)

    print(f"  {W_test:>4} {results_row[0]:>10.4f} {results_row[1]:>10.4f} "
          f"{results_row[2]:>10.4f} {results_row[3]:>10.4f}")


# ============================================================
# VERDICT
# ============================================================
print("\n" + "=" * 70)
print("VERDICT")
print("=" * 70)

best_overall = min(err_1mode, err_2mode, err_4mode, err_qr)
if best_overall == err_qr:
    winner = "5-mode QR"
elif best_overall == err_4mode:
    winner = "4-mode mod8"
elif best_overall == err_2mode:
    winner = "2-mode mod4"
else:
    winner = "1-mode"

print(f"""
  RESULTS:
    Diagonal only:          {baseline_err:.4f}
    1-mode (all primes):    {err_1mode:.4f}  ({(1-err_1mode/baseline_err)*100:+.1f}%)
    2-mode (mod 4 split):   {err_2mode:.4f}  ({(1-err_2mode/baseline_err)*100:+.1f}%)
    4-mode (mod 8 split):   {err_4mode:.4f}  ({(1-err_4mode/baseline_err)*100:+.1f}%)
    5-mode (QR families):   {err_qr:.4f}  ({(1-err_qr/baseline_err)*100:+.1f}%)

  BEST: {winner}

  The Ulam spiral insight: splitting primes by residue class
  gives each directional family its own coupling strength.
""")

print(f"Total time: {time.time() - t0:.1f}s")
